--------------------------------------------------------
--  File created - Sunday-March-06-2022   
--------------------------------------------------------
DROP SEQUENCE "ROOT"."CERTIFICATIONS_ID_SEQ";
DROP SEQUENCE "ROOT"."CONTACT_ID_SEQ";
DROP SEQUENCE "ROOT"."LANGUAGES_ID_SEQ";
DROP SEQUENCE "ROOT"."SKILL_ID_SEQ";
DROP SEQUENCE "ROOT"."USER_CONTACTS_SEQ";
DROP TABLE "ROOT"."CERTIFICATIONS" cascade constraints;
DROP TABLE "ROOT"."LANGUAGES" cascade constraints;
DROP TABLE "ROOT"."SKILLS" cascade constraints;
DROP TABLE "ROOT"."USERS" cascade constraints;
DROP TABLE "ROOT"."USER_CERTIFICATIONS" cascade constraints;
DROP TABLE "ROOT"."USER_CONTACTS" cascade constraints;
DROP TABLE "ROOT"."USER_LANGUAGES" cascade constraints;
DROP TABLE "ROOT"."USER_SKILLS" cascade constraints;
DROP PROCEDURE "ROOT"."INSERT_INTO_USER_CERT";
DROP PROCEDURE "ROOT"."SELECT_FROM_CERT";
--------------------------------------------------------
--  DDL for Sequence CERTIFICATIONS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROOT"."CERTIFICATIONS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 180 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CONTACT_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROOT"."CONTACT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LANGUAGES_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROOT"."LANGUAGES_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 120 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SKILL_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROOT"."SKILL_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1040 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USER_CONTACTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROOT"."USER_CONTACTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 160 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CERTIFICATIONS
--------------------------------------------------------

  CREATE TABLE "ROOT"."CERTIFICATIONS" 
   (	"CERT_ID" NUMBER(*,0), 
	"TYPE" VARCHAR2(200 BYTE), 
	"TITLE" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LANGUAGES
--------------------------------------------------------

  CREATE TABLE "ROOT"."LANGUAGES" 
   (	"LANG_ID" NUMBER(*,0), 
	"LANG_NAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SKILLS
--------------------------------------------------------

  CREATE TABLE "ROOT"."SKILLS" 
   (	"SKILL_ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "ROOT"."USERS" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"FULL_NAME" VARCHAR2(400 BYTE), 
	"O_NAME" VARCHAR2(250 BYTE), 
	"PASS" NUMBER(*,0), 
	"GENDER" VARCHAR2(1 BYTE), 
	"BIRTHDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_CERTIFICATIONS
--------------------------------------------------------

  CREATE TABLE "ROOT"."USER_CERTIFICATIONS" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"CERT_ID" NUMBER(*,0), 
	"CERT_TITLE" VARCHAR2(100 BYTE), 
	"CERT_SOURCE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_CONTACTS
--------------------------------------------------------

  CREATE TABLE "ROOT"."USER_CONTACTS" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"CONTACT_NUM" NUMBER(*,0), 
	"CONTACT_ADDRESS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_LANGUAGES
--------------------------------------------------------

  CREATE TABLE "ROOT"."USER_LANGUAGES" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"LANG_ID" NUMBER(*,0), 
	"LANG_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_SKILLS
--------------------------------------------------------

  CREATE TABLE "ROOT"."USER_SKILLS" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"SKILL_ID" NUMBER(*,0), 
	"SKILL_TITLE" VARCHAR2(100 BYTE), 
	"SKILL_DESC" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("SKILL_DESC") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into ROOT.CERTIFICATIONS
SET DEFINE OFF;
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (153,'sdfv','qawsd');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (158,'sdfv','qawsd');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (156,'sdfv','qawsd');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (149,'sdfv','qawsd');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (151,'sdfv','qawsd');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (125,'wedrfg','qwer');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (154,'sdfv','qawsd');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (127,'2werfg','qwedfr');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (148,'qwedfgb','ewfrgb');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (150,'sdfv','qawsd');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (152,'sdfv','qawsd');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (157,'sdfv','qawsd');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (159,'rtyhj','werftgh');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (164,' 7hucji8','tyhuj');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (166,'rtgefehytgfesdzdfvf','artegf');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (169,'tghynjmbk','tg5y6huj');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (170,'rgtyhju','4rtw5gy6hju k,');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (171,'fdgzs','rsg');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (123,'1234rtyh','23r4t5y6');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (140,'erf','wer');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (142,'efrgghn','efrwe');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (144,'wedfrgb','sdcf');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (146,'ertyh','`12we3r4tyh');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (155,'sdfv','qawsd');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (165,'78i9','56y7u8i78i');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (167,'rtgefehytgfesdzdfvf','artegf');
Insert into ROOT.CERTIFICATIONS (CERT_ID,TYPE,TITLE) values (168,'rtgefehytgfesdzdfvf','artegf');
REM INSERTING into ROOT.LANGUAGES
SET DEFINE OFF;
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (105,'aregeta');
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (106,'aetgraefd');
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (108,'aetgraefd');
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (101,'7u8i');
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (102,'78ij9');
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (111,'yhujki,l.');
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (113,'yujk');
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (115,'zsdfgf');
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (109,'aregeta');
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (103,'78i9o');
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (107,'aregeta');
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (110,'hytnjumk,nl .h');
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (112,'yhujnk');
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (114,'zfsg');
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (100,'y7u6xci8 ');
Insert into ROOT.LANGUAGES (LANG_ID,LANG_NAME) values (104,'aetgraefd');
REM INSERTING into ROOT.SKILLS
SET DEFINE OFF;
Insert into ROOT.SKILLS (SKILL_ID,TITLE) values (1020,'cv');
REM INSERTING into ROOT.USERS
SET DEFINE OFF;
Insert into ROOT.USERS (USER_ID,FULL_NAME,O_NAME,PASS,GENDER,BIRTHDATE) values ('ahmad2001','frghjhnmk,l;','ghjnkm',1234,'M',to_date('17-MAR-22','DD-MON-RR'));
REM INSERTING into ROOT.USER_CERTIFICATIONS
SET DEFINE OFF;
REM INSERTING into ROOT.USER_CONTACTS
SET DEFINE OFF;
Insert into ROOT.USER_CONTACTS (USER_ID,CONTACT_NUM,CONTACT_ADDRESS) values ('ahmad2001',140,'y7hu8xijo');
Insert into ROOT.USER_CONTACTS (USER_ID,CONTACT_NUM,CONTACT_ADDRESS) values ('ahmad2001',142,'fasedfgareg');
Insert into ROOT.USER_CONTACTS (USER_ID,CONTACT_NUM,CONTACT_ADDRESS) values ('ahmad2001',145,'yujki,lo.m;/');
Insert into ROOT.USER_CONTACTS (USER_ID,CONTACT_NUM,CONTACT_ADDRESS) values ('ahmad2001',146,'yujkml,.');
Insert into ROOT.USER_CONTACTS (USER_ID,CONTACT_NUM,CONTACT_ADDRESS) values ('ahmad2001',147,'zfghjkj7yhtrge');
Insert into ROOT.USER_CONTACTS (USER_ID,CONTACT_NUM,CONTACT_ADDRESS) values ('ahmad2001',143,'fasedfgareg');
Insert into ROOT.USER_CONTACTS (USER_ID,CONTACT_NUM,CONTACT_ADDRESS) values ('ahmad2001',144,'fasedfgareg');
Insert into ROOT.USER_CONTACTS (USER_ID,CONTACT_NUM,CONTACT_ADDRESS) values ('ahmad2001',141,'67h y8jiu9ok0p;');
REM INSERTING into ROOT.USER_LANGUAGES
SET DEFINE OFF;
REM INSERTING into ROOT.USER_SKILLS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index COMP_KEY_UL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."COMP_KEY_UL" ON "ROOT"."USER_LANGUAGES" ("USER_ID", "LANG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMP_KEY_UC
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."COMP_KEY_UC" ON "ROOT"."USER_CERTIFICATIONS" ("USER_ID", "CERT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMP_KEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."COMP_KEY" ON "ROOT"."USER_SKILLS" ("USER_ID", "SKILL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMP_KEY_UCO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."COMP_KEY_UCO" ON "ROOT"."USER_CONTACTS" ("USER_ID", "CONTACT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CERT_BIR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."CERT_BIR"     BEFORE INSERT ON CERTIFICATIONS    FOR EACH ROWBEGIN
    SELECT CERTIFICATIONS_ID_SEQ.NEXTVAL
    INTO   :new.CERT_ID
    FROM   dual;
END;
/
ALTER TRIGGER "ROOT"."CERT_BIR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LANG_BIR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."LANG_BIR"     BEFORE INSERT ON LANGUAGES    FOR EACH ROWBEGIN
    SELECT LANGUAGES_ID_SEQ.NEXTVAL
    INTO   :new.LANG_ID
    FROM   dual;
END;
/
ALTER TRIGGER "ROOT"."LANG_BIR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SKILL_BIR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."SKILL_BIR"     BEFORE INSERT ON SKILLS    FOR EACH ROWBEGIN
    SELECT SKILL_ID_SEQ.NEXTVAL
    INTO   :new.SKILL_ID
    FROM   dual;
END;
/
ALTER TRIGGER "ROOT"."SKILL_BIR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_CONTACTS_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."USER_CONTACTS_SEQ"     BEFORE INSERT ON USER_CONTACTS    FOR EACH ROWBEGIN
    SELECT USER_CONTACTS_SEQ.NEXTVAL
    INTO   :new.CONTACT_NUM
    FROM   dual;
END;
/
ALTER TRIGGER "ROOT"."USER_CONTACTS_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Procedure INSERT_INTO_USER_CERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "ROOT"."INSERT_INTO_USER_CERT" (USER_ID IN VARCHAR2,CERT_ID IN NUMBER,CERT_TITLE IN VARCHAR2,CERT_SOURCE IN VARCHAR2)
    is
begin
    insert into USER_CERTIFICATIONS values(USER_ID,CERT_ID,CERT_TITLE,CERT_SOURCE);
end;

/
--------------------------------------------------------
--  DDL for Procedure SELECT_FROM_CERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "ROOT"."SELECT_FROM_CERT" (IN_TITLE IN VARCHAR2,OUT_CERT_ID OUT NUMBER)
    is
begin
    SELECT CERT_ID INTO OUT_CERT_ID FROM CERTIFICATIONS where CERTIFICATIONS.TITLE=IN_TITLE;
end;

/
--------------------------------------------------------
--  Constraints for Table USER_CONTACTS
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_CONTACTS" ADD CONSTRAINT "COMP_KEY_UCO" PRIMARY KEY ("USER_ID", "CONTACT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_LANGUAGES
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_LANGUAGES" ADD CONSTRAINT "COMP_KEY_UL" PRIMARY KEY ("USER_ID", "LANG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_SKILLS
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_SKILLS" ADD CONSTRAINT "COMP_KEY" PRIMARY KEY ("USER_ID", "SKILL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKILLS
--------------------------------------------------------

  ALTER TABLE "ROOT"."SKILLS" ADD PRIMARY KEY ("SKILL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CERTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "ROOT"."CERTIFICATIONS" ADD PRIMARY KEY ("CERT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LANGUAGES
--------------------------------------------------------

  ALTER TABLE "ROOT"."LANGUAGES" ADD PRIMARY KEY ("LANG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "ROOT"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_CERTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_CERTIFICATIONS" ADD CONSTRAINT "COMP_KEY_UC" PRIMARY KEY ("USER_ID", "CERT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_CERTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_CERTIFICATIONS" ADD CONSTRAINT "FK_USER_CERTIFICATIONS_CE" FOREIGN KEY ("CERT_ID")
	  REFERENCES "ROOT"."CERTIFICATIONS" ("CERT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROOT"."USER_CERTIFICATIONS" ADD CONSTRAINT "FK_USER_CERTIFICATIONS_US" FOREIGN KEY ("USER_ID")
	  REFERENCES "ROOT"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_CONTACTS
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_CONTACTS" ADD CONSTRAINT "FK_USER_CONTACTS_US" FOREIGN KEY ("USER_ID")
	  REFERENCES "ROOT"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_LANGUAGES
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_LANGUAGES" ADD CONSTRAINT "FK_USER_LANGUAGES_LA" FOREIGN KEY ("LANG_ID")
	  REFERENCES "ROOT"."LANGUAGES" ("LANG_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROOT"."USER_LANGUAGES" ADD CONSTRAINT "FK_USER_LANGUAGES_US" FOREIGN KEY ("USER_ID")
	  REFERENCES "ROOT"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_SKILLS
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_SKILLS" ADD CONSTRAINT "FK_USER_SKILLS" FOREIGN KEY ("USER_ID")
	  REFERENCES "ROOT"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROOT"."USER_SKILLS" ADD CONSTRAINT "FK_USER_SKILLS_SK" FOREIGN KEY ("SKILL_ID")
	  REFERENCES "ROOT"."SKILLS" ("SKILL_ID") ON DELETE CASCADE ENABLE;
