--------------------------------------------------------
--  File created - Wednesday-February-23-2022   
--------------------------------------------------------
DROP SEQUENCE "ROOT"."CERTIFICATIONS_ID_SEQ";
DROP SEQUENCE "ROOT"."CONTACT_ID_SEQ";
DROP SEQUENCE "ROOT"."LANGUAGES_ID_SEQ";
DROP SEQUENCE "ROOT"."SKILL_ID_SEQ";
DROP TABLE "ROOT"."CERTIFICATIONS" cascade constraints;
DROP TABLE "ROOT"."CONTACTS" cascade constraints;
DROP TABLE "ROOT"."LANGUAGES" cascade constraints;
DROP TABLE "ROOT"."SKILLS" cascade constraints;
DROP TABLE "ROOT"."USERS" cascade constraints;
DROP TABLE "ROOT"."USER_CERTIFICATIONS" cascade constraints;
DROP TABLE "ROOT"."USER_CONTACTS" cascade constraints;
DROP TABLE "ROOT"."USER_LANGUAGES" cascade constraints;
DROP TABLE "ROOT"."USER_SKILLS" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence CERTIFICATIONS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROOT"."CERTIFICATIONS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CONTACT_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROOT"."CONTACT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LANGUAGES_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROOT"."LANGUAGES_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SKILL_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROOT"."SKILL_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CERTIFICATIONS
--------------------------------------------------------

  CREATE TABLE "ROOT"."CERTIFICATIONS" 
   (	"CERT_ID" NUMBER(*,0), 
	"TYPE" VARCHAR2(200 BYTE), 
	"TITLE" VARCHAR2(250 BYTE), 
	"SOURCE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTACTS
--------------------------------------------------------

  CREATE TABLE "ROOT"."CONTACTS" 
   (	"TYPE_ID" NUMBER, 
	"TYPE_DESC" VARCHAR2(50 BYTE), 
	"O_TYPE_DESC" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LANGUAGES
--------------------------------------------------------

  CREATE TABLE "ROOT"."LANGUAGES" 
   (	"LANG_ID" NUMBER(*,0), 
	"LANG_NAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SKILLS
--------------------------------------------------------

  CREATE TABLE "ROOT"."SKILLS" 
   (	"SKILL_ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(250 BYTE), 
	"DESCRIPTION" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "ROOT"."USERS" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"FULL_NAME" VARCHAR2(400 BYTE), 
	"O_NAME" VARCHAR2(250 BYTE), 
	"PASS" NUMBER(*,0), 
	"GENDER" VARCHAR2(1 BYTE), 
	"BIRTHDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_CERTIFICATIONS
--------------------------------------------------------

  CREATE TABLE "ROOT"."USER_CERTIFICATIONS" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"CERT_ID" NUMBER(*,0), 
	"CERT_TITLE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_CONTACTS
--------------------------------------------------------

  CREATE TABLE "ROOT"."USER_CONTACTS" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"CONTACT_NUM" NUMBER(*,0), 
	"TYPE_ID" NUMBER, 
	"CONTACT_ADDRESS" VARCHAR2(100 BYTE), 
	"TYPE_DESC" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_LANGUAGES
--------------------------------------------------------

  CREATE TABLE "ROOT"."USER_LANGUAGES" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"LANG_ID" NUMBER(*,0), 
	"LANG_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_SKILLS
--------------------------------------------------------

  CREATE TABLE "ROOT"."USER_SKILLS" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"SKILL_ID" NUMBER(*,0), 
	"SKILL_TITLE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ROOT.CERTIFICATIONS
SET DEFINE OFF;
REM INSERTING into ROOT.CONTACTS
SET DEFINE OFF;
REM INSERTING into ROOT.LANGUAGES
SET DEFINE OFF;
REM INSERTING into ROOT.SKILLS
SET DEFINE OFF;
REM INSERTING into ROOT.USERS
SET DEFINE OFF;
Insert into ROOT.USERS (USER_ID,FULL_NAME,O_NAME,PASS,GENDER,BIRTHDATE) values ('ahmad2001','Ahmad Natheer Yousef Jber','???? ???',1234,'M',to_date('27-DEC-01','DD-MON-RR'));
commit;
REM INSERTING into ROOT.USER_CERTIFICATIONS
SET DEFINE OFF;
REM INSERTING into ROOT.USER_CONTACTS
SET DEFINE OFF;
REM INSERTING into ROOT.USER_LANGUAGES
SET DEFINE OFF;
REM INSERTING into ROOT.USER_SKILLS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index COMP_KEY_UL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."COMP_KEY_UL" ON "ROOT"."USER_LANGUAGES" ("USER_ID", "LANG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMP_KEY_UC
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."COMP_KEY_UC" ON "ROOT"."USER_CERTIFICATIONS" ("USER_ID", "CERT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMP_KEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."COMP_KEY" ON "ROOT"."USER_SKILLS" ("USER_ID", "SKILL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMP_KEY_UCO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROOT"."COMP_KEY_UCO" ON "ROOT"."USER_CONTACTS" ("USER_ID", "CONTACT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CERT_BIR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."CERT_BIR" 
    BEFORE INSERT ON CERTIFICATIONS
    FOR EACH ROW
BEGIN
    SELECT CERTIFICATIONS_ID_SEQ.NEXTVAL
    INTO   :new.CERT_ID
    FROM   dual;
END;
/
ALTER TRIGGER "ROOT"."CERT_BIR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONT_BIR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."CONT_BIR" 
    BEFORE INSERT ON CONTACTS
    FOR EACH ROW
BEGIN
    SELECT CONTACT_ID_SEQ.NEXTVAL
    INTO   :new.TYPE_ID
    FROM   dual;
END;
/
ALTER TRIGGER "ROOT"."CONT_BIR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DEPT_BIR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."DEPT_BIR" 
    BEFORE INSERT ON SKILLS
    FOR EACH ROW
BEGIN
    SELECT SKILL_ID_SEQ.NEXTVAL
    INTO   :new.SKILL_ID
    FROM   dual;
END;
/
ALTER TRIGGER "ROOT"."DEPT_BIR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LANG_BIR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ROOT"."LANG_BIR" 
    BEFORE INSERT ON LANGUAGES
    FOR EACH ROW
BEGIN
    SELECT LANGUAGES_ID_SEQ.NEXTVAL
    INTO   :new.LANG_ID
    FROM   dual;
END;
/
ALTER TRIGGER "ROOT"."LANG_BIR" ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_CONTACTS
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_CONTACTS" ADD CONSTRAINT "COMP_KEY_UCO" PRIMARY KEY ("USER_ID", "CONTACT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_SKILLS
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_SKILLS" ADD CONSTRAINT "COMP_KEY" PRIMARY KEY ("USER_ID", "SKILL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_CERTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_CERTIFICATIONS" ADD CONSTRAINT "COMP_KEY_UC" PRIMARY KEY ("USER_ID", "CERT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKILLS
--------------------------------------------------------

  ALTER TABLE "ROOT"."SKILLS" ADD PRIMARY KEY ("SKILL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "ROOT"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_LANGUAGES
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_LANGUAGES" ADD CONSTRAINT "COMP_KEY_UL" PRIMARY KEY ("USER_ID", "LANG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LANGUAGES
--------------------------------------------------------

  ALTER TABLE "ROOT"."LANGUAGES" ADD PRIMARY KEY ("LANG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTACTS
--------------------------------------------------------

  ALTER TABLE "ROOT"."CONTACTS" ADD PRIMARY KEY ("TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CERTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "ROOT"."CERTIFICATIONS" ADD PRIMARY KEY ("CERT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_CERTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_CERTIFICATIONS" ADD CONSTRAINT "FK_USER_CERTIFICATIONS_CE" FOREIGN KEY ("CERT_ID")
	  REFERENCES "ROOT"."CERTIFICATIONS" ("CERT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROOT"."USER_CERTIFICATIONS" ADD CONSTRAINT "FK_USER_CERTIFICATIONS_US" FOREIGN KEY ("USER_ID")
	  REFERENCES "ROOT"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_CONTACTS
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_CONTACTS" ADD CONSTRAINT "FK_USER_CONTACTS_CO" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "ROOT"."CONTACTS" ("TYPE_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROOT"."USER_CONTACTS" ADD CONSTRAINT "FK_USER_CONTACT_US" FOREIGN KEY ("USER_ID")
	  REFERENCES "ROOT"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_LANGUAGES
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_LANGUAGES" ADD CONSTRAINT "FK_USER_LANGUAGES_LA" FOREIGN KEY ("LANG_ID")
	  REFERENCES "ROOT"."LANGUAGES" ("LANG_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROOT"."USER_LANGUAGES" ADD CONSTRAINT "FK_USER_LANGUAGES_US" FOREIGN KEY ("USER_ID")
	  REFERENCES "ROOT"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_SKILLS
--------------------------------------------------------

  ALTER TABLE "ROOT"."USER_SKILLS" ADD CONSTRAINT "FK_USER_SKILLS" FOREIGN KEY ("USER_ID")
	  REFERENCES "ROOT"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ROOT"."USER_SKILLS" ADD CONSTRAINT "FK_USER_SKILLS_SK" FOREIGN KEY ("SKILL_ID")
	  REFERENCES "ROOT"."SKILLS" ("SKILL_ID") ON DELETE CASCADE ENABLE;
